Feature/skip steps (#5)
* - adds skip_steps_file PARAM to config.
- removes the --dry-run (relocating to Snakefile).

* Changes to address rule skipping for specific accessions in bulk recalculations.

* - Includes function skip to simplify code
- Removes 'return [" "]'
- Makes skip_accession global

* Removes existing braces in IF statement. Braces not used for variable access have to be escaped by repeating them, i.e. {{print $1}}.

* Var $organism is now defined before it is used in $gff_file

* Fixes syntax error.

* Missing 's' in skip_accession.

* Resolves the error '' 'NoneType' object is not subscriptable" that occurs when the parameter 'skip_steps_file' is not provided in --config of Snake-sorting-hat.

diff --git a/Snakefile-sorting-hat b/Snakefile-sorting-hat
--- a/Snakefile-sorting-hat
+++ b/Snakefile-sorting-hat
@@ -66,7 +66,16 @@ def get_bioentities_property_path():
     return config['bioentities_properties']
 
 def get_delete_previous_output():
-    return config['delete_previous_output']
+    if 'delete_previous_output' in config:
+        return config['delete_previous_output']
+    else:
+        return None
+
+def get_skip_steps_file():
+    if 'skip_steps_file' in config:
+        return config['skip_steps_file']
+    else:
+        return None 
 
 
 def get_outputs():
@@ -112,29 +121,30 @@ rule get_experiment_metadata:
         export ATLAS_EXPS={params.atlas_exps}
         source {workflow.basedir}/bin/metadata_retrieval_functions.sh
 
+        perl {workflow.basedir}/bin/get_exptype_contrasts_assays.pl {wildcards.accession} {input.config_file} {output.metadata}
+        if [ -e "{wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv" ]; then
+            echo "Trying with condensed..."
+            organism=$(get_organism_from_condensed_sdrf "{wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv")
+        elif [ -e "{wildcards.accession}/{wildcards.accession}-configuration.xml" ]; then
+            echo "Trying with perl (produces organism with capitals and spaces)"
+            organism=$(perl {workflow.basedir}/bin/get_experiment_info.pl --experiment {wildcards.accession} --xmlfile {wildcards.accession}/{wildcards.accession}-configuration.xml --organism | sed 's/ /_/g' | tr '[:upper:]' '[:lower:]')
+        else
+            echo "Nothing worked..."
+            >&2 echo "Can't retrieve organism: neither {wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv nor {wildcards.accession}/{wildcards.accession}-configuration.xml not found "
+            exit 1
+        fi
+
         gff_file=$( find {input.gtf_dir}/$organism -iname "$organism.*.gff3" | head -n1)
         magetabfiles=$( perl {workflow.basedir}/bin/get_experiment_info.pl --experiment {wildcards.accession} --xmlfile {wildcards.accession}/{wildcards.accession}-configuration.xml --magetabfiles)
         idf=$( echo $magetabfiles | awk -F',' '{{ print $1 }}' )
         sdrf=$( echo $magetabfiles | awk -F',' '{{ print $2 }}' )
-        if [ -z "${gff_file}" ] || [ -z "${idf}" ] || [ -z "${sdrf}" ]; then
+        if [ -z "$gff_file" ] || [ -z "$idf" ] || [ -z "$sdrf" ]; then
             echo "GFF: $gff_file"
             echo "IDF: $idf"
             echo "SDRF: $sdrf"
             echo "GFF, IDF or SDRF not found. YAML not created"
             exit 1
         else
-            perl {workflow.basedir}/bin/get_exptype_contrasts_assays.pl {wildcards.accession} {input.config_file} {output.metadata}
-            if [ -e "{wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv" ]; then
-                echo "Trying with condensed..."
-                organism=$(get_organism_from_condensed_sdrf "{wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv")
-            elif [ -e "{wildcards.accession}/{wildcards.accession}-configuration.xml" ]; then
-                echo "Trying with perl (produces organism with capitals and spaces)"
-                organism=$(perl {workflow.basedir}/bin/get_experiment_info.pl --experiment {wildcards.accession} --xmlfile {wildcards.accession}/{wildcards.accession}-configuration.xml --organism | sed 's/ /_/g' | tr '[:upper:]' '[:lower:]')
-            else
-                echo "Nothing worked..."
-                >&2 echo "Can't retrieve organism: neither {wildcards.accession}/{wildcards.accession}.condensed-sdrf.tsv nor {wildcards.accession}/{wildcards.accession}-configuration.xml not found "
-                exit 1
-            fi
             echo "organism: $organism" >> {output.metadata}
             echo "gff: $gff_file" >> {output.metadata}
             echo "idf: $idf" >> {output.metadata}
@@ -150,6 +160,7 @@ rule produce_recalculations_call:
     params:
         bioentities_properties=get_bioentities_property_path(),
         delete_previous_output=get_delete_previous_output(),
+        skip_steps_file=get_skip_steps_file(),
         log_handler_script=get_log_handler_script()
         # snakemake_opts=config["sm_options"],
         # tool=get_tool("{accession}"),
@@ -171,6 +182,7 @@ rule produce_recalculations_call:
             metadata_summary=../{input.metadata} \
             bioentities_properties={params.bioentities_properties} \
             delete_previous_output={params.delete_previous_output} \
+            skip_steps_file={params.skip_steps_file} \
             -s {workflow.basedir}/Snakefile {get_log_handler_script()}
         popd
         """
