add differential proteomics' rules and relevant control logic

diff --git a/Snakefile-proteomics b/Snakefile-proteomics
--- a/Snakefile-proteomics
+++ b/Snakefile-proteomics
@@ -203,3 +203,86 @@ rule final_check_tsv_data_file_not_empty_of_data:
 
 # differential proteomics rules
 
+rule rename_differential_proteomics_files:
+
+    conda: "envs/proteomics_processing.yaml"
+    log: "logs/{accession}-rename_differential_proteomics_files.log"
+    output:
+        temp("{accession}-rename_differential_proteomics_files.done")
+    shell:
+        """
+        set -e # snakemake on the cluster doesn't stop on error when --keep-going is set
+        exec &> "{log}"
+
+        source {workflow.basedir}/bin/proteomics_functions.sh
+        echo "renaming files for {wildcards.accession}"
+        rename_files_differential {wildcards.accession}
+        touch {output}
+        """
+
+# rule round_log2_fold_changes_rnaseq (Snakefile use as well for diff proteomics)
+
+rule decorate_differential_proteomics:
+    """
+    Decorate differential proteomics experiment with gene name from the latest Ensembl release
+    """
+    container: "docker://quay.io/ebigxa/ensembl-update-env:amm1.1.2"
+    log: "logs/{accession}-decorate_differential_proteomics.log"
+    resources: mem_mb=get_mem_mb   
+    input:
+        rules.round_log2_fold_changes_rnaseq.output.unrounded,
+        "{accession}-analytics.tsv.undecorated"
+    params:
+        organism=get_organism()
+    output:
+        "{accession}-analytics.tsv",
+        "{accession}-analytics.tsv.unrounded",
+        temp("logs/{accession}-decorate_differential_proteomics.done")
+    shell:
+        """
+        set -e # snakemake on the cluster doesn't stop on error when --keep-going is set
+        exec &> "{log}"
+        source {workflow.basedir}/bin/reprocessing_routines.sh
+        source {workflow.basedir}/atlas-bash-util/generic_routines.sh
+
+        geneNameFile=$( get_geneNameFile_given_organism {params.organism}  )
+
+        echo $geneNameFile
+
+        test -s "$geneNameFile" || (  >&2 echo "$0 gene name file not found: $geneNameFile" ; exit 1 )
+
+        for i in {input}
+        do  
+            echo "${{i}}"
+            decoratedFile=`echo "${{i}}" | sed 's/\.undecorated//'`
+            echo "$decoratedFile"
+
+            # pass avail custom memory to JVM for Ammonite REPL
+            export JAVA_OPTS="-Xmx{resources.mem_mb}M"
+            amm -s {workflow.basedir}/bin/decorateFile.sc \
+                --geneNameFile "$geneNameFile" \
+                --source "${{i}}" \
+                | awk 'NR == 1; NR > 1 {{print $0 | "sort -n"}}' \
+                > $decoratedFile.swp
+
+            decoratedFileLength=$(wc -l "$decoratedFile.swp" | cut -f 1 -d ' ' )
+            if [ -s "$decoratedFile.swp" ] && [ "$decoratedFileLength" -gt 1 ]; then
+                mv $decoratedFile.swp $decoratedFile
+            else                                                                                                                                                                                                                    
+                echo "ERROR: decorate_differential_proteomics for {wildcards.accession} and undecorated input ${{i}} "
+                exit 1                                                                                                                                                                                                              
+            fi
+        done
+        touch {output[2]}                                                                                                                                                                                                       
+        """                                                                                                                                                                                                                                   
+
+# rule percentile_ranks (Snakefile use as well for diff proteomics)
+
+
+
+
+ # Perform GSEA against Go/Interpro/Reactome
+
+ # Generate Genome browser tracks (bedGraph) for the experiment
+
+ 
diff --git a/Snakefile-sorting-hat b/Snakefile-sorting-hat
--- a/Snakefile-sorting-hat
+++ b/Snakefile-sorting-hat
@@ -152,7 +152,8 @@ rule get_experiment_metadata:
         atlas_meta_config = config['atlas_meta_config'],
         atlas_prod = config['atlas_prod'],
         atlas_exps = config['atlas_exps'],
-        check_species_file=config['check_sp_file']
+        check_species_file=config['check_sp_file'],
+        prot_magetab_files=config['prot_magetabfiles']
     input:
         config_file = "{accession}/{accession}-configuration.xml",
         gtf_dir = config['gtf_dir']
@@ -171,7 +172,7 @@ rule get_experiment_metadata:
         source {workflow.basedir}/atlas-bash-util/generic_routines.sh
 
 
-        # proteomics experiments do not need to include exptype contrasts assays in the summary yaml
+        # proteomics experiments do not need to include exp type assays/contrasts in the summary yaml
         prot_exp_type='experimentType="proteomics'
         if grep -q "$prot_exp_type" {input.config_file} ; then
             rm -f {output.metadata}
@@ -213,27 +214,26 @@ rule get_experiment_metadata:
 	    echo "GTF file location sourced"
 
         if grep -q "$prot_exp_type" {input.config_file} ; then
-            echo "Experiment type is proteomics. Skipping IDF and SDRF files in the summary yaml"
-            echo "organism: $organism" >> {output.metadata}
-            echo "gff: $gff_file" >> {output.metadata}
+            idf={params.prot_magetab_files}/{wildcards.accession}/{wildcards.accession}.idf.txt
+            sdrf={params.prot_magetab_files}/{wildcards.accession}/{wildcards.accession}.sdrf.txt
         else
             magetabfiles=$( perl {workflow.basedir}/bin/get_experiment_info.pl --experiment {wildcards.accession} --xmlfile {wildcards.accession}/{wildcards.accession}-configuration.xml --magetabfiles --not-strict)
-	    
             echo "MAGETAB location sourced"
             idf=$( echo $magetabfiles | awk -F',' '{{ print $1 }}' )
             sdrf=$( echo $magetabfiles | awk -F',' '{{ print $2 }}' )
-            if [ -z "$gff_file" ] || [ -z "$idf" ] || [ -z "$sdrf" ]; then
-                echo "GFF: $gff_file"
-                echo "IDF: $idf"
-                echo "SDRF: $sdrf"
-                echo "GFF, IDF or SDRF not found. YAML not created...Exiting with error"
-                exit 1
-            else
-                echo "organism: $organism" >> {output.metadata}
-                echo "gff: $gff_file" >> {output.metadata}
-                echo "idf: $idf" >> {output.metadata}
-                echo "sdrf: $sdrf" >> {output.metadata}
-            fi
+        fi
+
+        if [ -z "$gff_file" ] || [ -z "$idf" ] || [ -z "$sdrf" ]; then
+            echo "GFF: $gff_file"
+            echo "IDF: $idf"
+            echo "SDRF: $sdrf"
+            echo "GFF, IDF or SDRF not found. YAML not created...Exiting with error"
+            exit 1
+        else
+            echo "organism: $organism" >> {output.metadata}
+            echo "gff: $gff_file" >> {output.metadata}
+            echo "idf: $idf" >> {output.metadata}
+            echo "sdrf: $sdrf" >> {output.metadata}
         fi
         """
 
