Amend logs locations

diff --git a/Snakefile-sorting-hat b/Snakefile-sorting-hat
--- a/Snakefile-sorting-hat
+++ b/Snakefile-sorting-hat
@@ -87,7 +87,7 @@ rule get_experiment_metadata:
         "docker://quay.io/biocontainers/perl-atlas-modules:0.2.0--h1b792b2_0"
     conda:
         "envs/perl-atlas-modules.yaml"
-    log: "{accession}/log/get_experiment_metadata.log"
+    log: "{accession}/logs/get_experiment_metadata.log"
     params:
         atlas_meta_config = config['atlas_meta_config'],
         atlas_prod = config['atlas_prod']
@@ -100,7 +100,8 @@ rule get_experiment_metadata:
         """
         # needed for container conda env activation
         # /usr/local/env-execute
-        mkdir -p {accession}/log
+        set -e # snakemake on the cluster doesn't stop on error when --keep-going is set
+        mkdir -p {wildcards.accession}/logs
         exec &> {log}
         export ATLAS_META_CONFIG={params.atlas_meta_config}
         export ATLAS_PROD={params.atlas_prod}
@@ -132,7 +133,7 @@ rule produce_recalculations_call:
     input:
         metadata = "{accession}/{accession}.metadata_summary.yaml",
         working_directory = "{accession}"
-    log: "{accession}/produce_recalculations_call.log"
+    log: "{accession}/logs/produce_recalculations_call.log"
     params:
         bioentities_properties=get_bioentities_property_path(),
         log_handler_script=get_log_handler_script()
@@ -146,6 +147,8 @@ rule produce_recalculations_call:
         touch("{accession}/{accession}.recalculations.done")
     run:
         command_line=f"""
+        set -e # snakemake on the cluster doesn't stop on error when --keep-going is set
+        mkdir -p {wildcards.accession}/logs
         exec &> {log}
         pushd {input.working_directory}
         snakemake {config['sm_options']} --config \
